name: wf-ci-development
on:
  pull_request:
    branches:
      - develop 
jobs:
  ci-development-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v4
      - name: Lint html and css file 
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Test Build ops
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"